### PR TITLE
feature/strictscale: add possibility to restrict user scale, fix issue #85

### PR DESCRIPTION
**Pull request by EArminjon**
Actual behavior : 
User can scale image in or out. When user release scale gesture, app will rescale if current user scale choice is behind defined limit (maxScale and minScale).

Proposition : 
A new property to prevent the user to scale behind theses limit.

### CODE REVIEW

**Comment by EArminjon** [comment]
Ready

**Comment by EArminjon** [comment]
@renancaraujo can you take a look please :'( ?

**Review by renancaraujo — APPROVED** [review]

**Comment by renancaraujo** [comment]
We have wey too many proeprties on those widgets, we will have to do a cleanup eventually

**Comment by EArminjon** [comment]
@renancaraujo to you plan to release this PR on pub dev :) ?

**Comment by EArminjon** [comment]
@renancaraujo  seems like the auto deployment didn't push the new version on pub dev.

**Comment by EArminjon** [comment]
@renancaraujo  ?

**Comment by phamconganh** [comment]
@EArminjon `strictScale` makes it impossible to scale back to `minScale`. Example: `minScale` 1, but only `zoomOut` to 1.0043980003016804

**Comment by EArminjon** [comment]
> @EArminjon `strictScale` makes it impossible to scale back to `minScale`. Example: `minScale` 1, but only `zoomOut` to 1.0043980003016804. I think `clamp` `newScale` and update if different from previous scale at line code:
> ```
>     if (widget.strictScale && (newScale > widget.scaleBoundaries.maxScale ||
>         newScale < widget.scaleBoundaries.minScale)) {
>       return;
>     }
> ```

Create an issue with reproductible steps please. Commenting merged PR is not a good practice.

**Pull request merged**
